server:
  port : 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koting?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
  mail:
    host: smtp.gmail.com
    port: 587
    username: lgwl81@gmail.com
    password: ghdghkgud123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /static/**

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


