# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Koting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Koting
pod 'Alamofire'
pod 'MaterialComponents/Buttons'
pod 'PanModal'
pod 'NVActivityIndicatorView'
pod 'MaterialComponents/BottomAppBar'
pod 'PagingKit'

# For Chat
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'MessageKit'
pod 'RealmSwift'
pod 'SDWebImage'
end
