# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Koting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Koting
pod 'RxSwift'
pod 'Alamofire'
pod 'MaterialComponents/Buttons'
pod 'PanModal'
end
